##########################
#
# configuration file for pipeline_singlecell
#
##########################

# Specify where the fastq files are located.
# fastq files need to have the suffix read1: .fastq.1.gz read2: .fastq.2.gz
data: data.dir

memory: 20G

# Specify the mirror for bioMart
mirror: useast

#Specifiy the number of counts for filtering
UMI_filter: 100
