##########################
#
# configuration file for pipeline_singlecell
#
##########################

# Specify where the fastq files are located.
# fastq files need to have the suffix read1: .fastq.1.gz read2: .fastq.2.gz
data: data.dir

memory: 20G

# Specify the mirror for bioMart
mirror: useast

#Specifiy the number of counts for filtering when Seurat object is created
so_filter: 100

#Specificy the number of counts if more stringent filter is required
UMI_filter: 100

#Specify the format of output files
output: seurat_object
