##########################
#
# configuration file for pipeline_quantvisium
#
##########################

# Specify where the fastq files are located.
# fastq files need to have the suffix read1: .fastq.1.gz read2: .fastq.2.gz
data: data.dir


spaceranger_module: spaceranger/1.2.2

# Location of the genome file for running spaceranger
trans_file: /t1-data/project/tendonhca/shared/refdata-gex-GRCh38-2020-A

